// This file is autogenerated by scripts/svg-sprite. Do not edit this file manually!

export const ID_SEPARATOR = "--";
export const SPRITE_FILE = "sprite.svg";

export type SvgSpriteName =
  | "logo"
  | "tablerAlertCircle"
  | "tablerArrowsSort"
  | "tablerBold"
  | "tablerChevronDown"
  | "tablerChevronLeft"
  | "tablerChevronRight"
  | "tablerCircleCheck"
  | "tablerHorizontalRule"
  | "tablerInfoCircle"
  | "tablerItalic"
  | "tablerList"
  | "tablerListNumbers"
  | "tablerMenu2"
  | "tablerPasswordHideIcon"
  | "tablerPasswordShowIcon"
  | "tablerPilcrow"
  | "tablerSearch"
  | "tablerSettings"
  | "tablerSortAscending"
  | "tablerSortDescending"
  | "tablerStrikethrough"
  | "tablerSubscript"
  | "tablerSuperscript"
  | "tablerUnderline"
  | "tablerX"
  | "test/logo";

export const SVG_SPRITE_DEFINITIONS: Record<SvgSpriteName, { viewBox: string }> = {
  logo: { viewBox: "0 0 200 200" },
  tablerAlertCircle: { viewBox: "0 0 24 24" },
  tablerArrowsSort: { viewBox: "0 0 24 24" },
  tablerBold: { viewBox: "0 0 24 24" },
  tablerChevronDown: { viewBox: "0 0 24 24" },
  tablerChevronLeft: { viewBox: "0 0 24 24" },
  tablerChevronRight: { viewBox: "0 0 24 24" },
  tablerCircleCheck: { viewBox: "0 0 24 24" },
  tablerHorizontalRule: { viewBox: "0 0 24 24" },
  tablerInfoCircle: { viewBox: "0 0 24 24" },
  tablerItalic: { viewBox: "0 0 24 24" },
  tablerList: { viewBox: "0 0 24 24" },
  tablerListNumbers: { viewBox: "0 0 24 24" },
  tablerMenu2: { viewBox: "0 0 24 24" },
  tablerPasswordHideIcon: { viewBox: "0 0 24 24" },
  tablerPasswordShowIcon: { viewBox: "0 0 24 24" },
  tablerPilcrow: { viewBox: "0 0 24 24" },
  tablerSearch: { viewBox: "0 0 24 24" },
  tablerSettings: { viewBox: "0 0 24 24" },
  tablerSortAscending: { viewBox: "0 0 24 24" },
  tablerSortDescending: { viewBox: "0 0 24 24" },
  tablerStrikethrough: { viewBox: "0 0 24 24" },
  tablerSubscript: { viewBox: "0 0 24 24" },
  tablerSuperscript: { viewBox: "0 0 24 24" },
  tablerUnderline: { viewBox: "0 0 24 24" },
  tablerX: { viewBox: "0 0 24 24" },
  "test/logo": { viewBox: "0 0 200 200" },
};
